title: NBULA 
description: Non-Binary Union LA [DRAFT/unofficial website]

exclude:
  README.md
github:
  is_project_page: false
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
show_downloads: false
theme: jekyll-theme-cayman
