exclude:
  README.md
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
theme: jekyll-theme-slate
title: NBULA [DRAFT/unofficial website] 
description: Non-Binary Union LA
