# https://docs.docker.com/compose/compose-file/compose-file-v3/
version: "3.8"

services:

  jekyll:
    build: .
    command: jekyll serve --incremental
    container_name: jekyll-nbula
    ports:
      - "4000:4000"
    restart: always
    tty: true
    volumes:
      # https://github.com/docker/for-mac/issues/1592
      - ./:/srv/jekyll
