# Also see:
#   Dockerfile
#
# https://docs.docker.com/compose/compose-file/compose-file-v2/

version: "2.4"

services:

  jekyll:
    build: .
    container_name: jekyll-nbula
    ports:
      - "4000:4000"
    restart: on-failure
    tty: true
    volumes:
      # https://github.com/docker/for-mac/issues/1592
      - ./:/srv/jekyll
